var e;e||=typeof Module != 'undefined' ? Module : {};var aa="object"==typeof window,k="undefined"!=typeof WorkerGlobalScope,m="object"==typeof process&&process.versions?.node&&"renderer"!=process.type,p="./this.program",q=(a,b)=>{throw b;},r="undefined"!=typeof document?document.currentScript?.src:void 0;"undefined"!=typeof __filename?r=__filename:k&&(r=self.location.href);var t="",u,v;
if(m){var fs=require("fs");t=__dirname+"/";v=a=>{a=w(a)?new URL(a):a;return fs.readFileSync(a)};u=async a=>{a=w(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(p=process.argv[1].replace(/\\/g,"/"));process.argv.slice(2);"undefined"!=typeof module&&(module.exports=e);q=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||k){try{t=(new URL(".",r)).href}catch{}k&&(v=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
u=async a=>{if(w(a))return new Promise((c,d)=>{var f=new XMLHttpRequest;f.open("GET",a,!0);f.responseType="arraybuffer";f.onload=()=>{200==f.status||0==f.status&&f.response?c(f.response):d(f.status)};f.onerror=d;f.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}var x=console.log.bind(console),y=console.error.bind(console),z,A=!1,w=a=>a.startsWith("file://"),B,C,D,E,F;
function G(){var a=B.buffer;new Int8Array(a);new Int16Array(a);e.HEAPU8=C=new Uint8Array(a);new Uint16Array(a);D=new Int32Array(a);E=new Uint32Array(a);new Float32Array(a);new Float64Array(a);F=new BigInt64Array(a);new BigUint64Array(a)}var H=0,I=null;function J(a){e.onAbort?.(a);a="Aborted("+a+")";y(a);A=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var K;
async function ba(a){if(!z)try{var b=await u(a);return new Uint8Array(b)}catch{}if(a==K&&z)a=new Uint8Array(z);else if(v)a=v(a);else throw"both async and sync fetching of the wasm failed";return a}async function ca(a,b){try{var c=await ba(a);return await WebAssembly.instantiate(c,b)}catch(d){y(`failed to asynchronously prepare wasm: ${d}`),J(d)}}
async function da(a){var b=K;if(!z&&"function"==typeof WebAssembly.instantiateStreaming&&!w(b)&&!m)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){y(`wasm streaming compile failed: ${d}`),y("falling back to ArrayBuffer instantiation")}return ca(b,a)}class fa{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var N=a=>{for(;0<a.length;)a.shift()(e)},O=[],P=[],ha=()=>{var a=e.preRun.shift();P.push(a)},Q=!0;class ia{constructor(a){this.L=a-24}}
var R=0,ja=0,ka="undefined"!=typeof TextDecoder?new TextDecoder:void 0,la=(a,b=0,c=NaN)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&ka)return ka.decode(a.subarray(b,c));for(d="";b<c;){var f=a[b++];if(f&128){var g=a[b++]&63;if(192==(f&224))d+=String.fromCharCode((f&31)<<6|g);else{var h=a[b++]&63;f=224==(f&240)?(f&15)<<12|g<<6|h:(f&7)<<18|g<<12|h<<6|a[b++]&63;65536>f?d+=String.fromCharCode(f):(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else d+=String.fromCharCode(f)}return d},
S=(a,b,c)=>{var d=C;if(!(0<c))return 0;var f=b;c=b+c-1;for(var g=0;g<a.length;++g){var h=a.codePointAt(g);if(127>=h){if(b>=c)break;d[b++]=h}else if(2047>=h){if(b+1>=c)break;d[b++]=192|h>>6;d[b++]=128|h&63}else if(65535>=h){if(b+2>=c)break;d[b++]=224|h>>12;d[b++]=128|h>>6&63;d[b++]=128|h&63}else{if(b+3>=c)break;d[b++]=240|h>>18;d[b++]=128|h>>12&63;d[b++]=128|h>>6&63;d[b++]=128|h&63;g++}}d[b]=0;return b-f},T={},ma=()=>{if(!U){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",
LANG:("object"==typeof navigator&&navigator.language||"C").replace("-","_")+".UTF-8",_:p||"./this.program"},b;for(b in T)void 0===T[b]?delete a[b]:a[b]=T[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);U=c}return U},U,na=[null,[],[]],V=[],W,X,oa=[];e.noExitRuntime&&(Q=e.noExitRuntime);e.print&&(x=e.print);e.printErr&&(y=e.printErr);e.wasmBinary&&(z=e.wasmBinary);e.thisProgram&&(p=e.thisProgram);
e.addFunction=(a,b)=>{if(!X){X=new WeakMap;var c=W.length;if(X)for(var d=0;d<0+c;d++){var f;(f=V[d])||(V[d]=f=W.get(d));f&&X.set(f,d)}}if(c=X.get(a)||0)return c;if(oa.length)c=oa.pop();else{try{W.grow(1)}catch(n){if(!(n instanceof RangeError))throw n;throw"Unable to grow wasm table. Set ALLOW_TABLE_GROWTH.";}c=W.length-1}try{d=c,W.set(d,a),V[d]=W.get(d)}catch(n){if(!(n instanceof TypeError))throw n;if("function"==typeof WebAssembly.Function){var g=WebAssembly.Function;d={i:"i32",j:"i64",f:"f32",d:"f64",
e:"externref",p:"i32"};f={parameters:[],results:"v"==b[0]?[]:[d[b[0]]]};for(var h=1;h<b.length;++h)f.parameters.push(d[b[h]]);b=new g(f,a)}else{d=[1];f=b.slice(0,1);b=b.slice(1);h={i:127,p:127,j:126,f:125,d:124,e:111};d.push(96);var l=b.length;128>l?d.push(l):d.push(l%128|128,l>>7);for(g of b)d.push(h[g]);"v"==f?d.push(0):d.push(1,h[f]);b=[0,97,115,109,1,0,0,0,1];g=d.length;128>g?b.push(g):b.push(g%128|128,g>>7);b.push(...d);b.push(2,7,1,1,101,1,102,0,0,7,5,1,1,102,0,0);b=new WebAssembly.Module(new Uint8Array(b));
b=(new WebAssembly.Instance(b,{e:{f:a}})).exports.f}g=c;W.set(g,b);V[g]=W.get(g)}X.set(a,c);return c};e.UTF8ToString=(a,b)=>a?la(C,a,b):"";
var pa={a:(a,b,c)=>{var d=new ia(a);E[d.L+16>>2]=0;E[d.L+4>>2]=b;E[d.L+8>>2]=c;R=a;ja++;throw R;},d:function(){return 0},g:function(){return 0},h:function(){},i:()=>J(""),j:(a,b,c,d)=>{var f=(new Date).getFullYear(),g=(new Date(f,0,1)).getTimezoneOffset();f=(new Date(f,6,1)).getTimezoneOffset();E[a>>2]=60*Math.max(g,f);D[b>>2]=Number(g!=f);b=h=>{var l=Math.abs(h);return`UTC${0<=h?"-":"+"}${String(Math.floor(l/60)).padStart(2,"0")}${String(l%60).padStart(2,"0")}`};a=b(g);b=b(f);f<g?(S(a,c,17),S(b,
d,17)):(S(a,d,17),S(b,c,17))},k:function(a,b,c){if(!(0<=a&&3>=a))return 28;F[c>>3]=BigInt(Math.round(1E6*(0===a?Date.now():performance.now())));return 0},l:a=>{var b=C.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-B.buffer.byteLength+65535)/65536|0;try{B.grow(d);G();var f=1;break a}catch(g){}f=void 0}if(f)return!0}return!1},n:(a,b)=>{var c=0,d=0,f;for(f of ma()){var g=b+c;E[a+
d>>2]=g;c+=S(f,g,Infinity)+1;d+=4}return 0},e:(a,b)=>{var c=ma();E[a>>2]=c.length;a=0;for(var d of c){for(var f=c=0;f<d.length;++f){var g=d.charCodeAt(f);127>=g?c++:2047>=g?c+=2:55296<=g&&57343>=g?(c+=4,++f):c+=3}a+=c+1}E[b>>2]=a;return 0},b:()=>52,f:()=>52,m:function(){return 70},c:(a,b,c,d)=>{for(var f=0,g=0;g<c;g++){var h=E[b>>2],l=E[b+4>>2];b+=8;for(var n=0;n<l;n++){var ea=a,L=C[h+n],M=na[ea];0===L||10===L?((1===ea?x:y)(la(M)),M.length=0):M.push(L)}f+=l}E[d>>2]=f;return 0},o:a=>{Q||(e.onExit?.(a),
A=!0);q(a,new fa(a))}},Y;
(async function(){function a(c){Y=c.exports;B=Y.p;G();W=Y.K;c=Y;e._memory_alloc=c.r;e._set_error_callback=c.s;e._set_result_callback=c.t;e._run=c.u;e._free=c.v;e._BinaryenSizeofLiteral=c.w;e._BinaryenSizeofAllocateAndWriteResult=c.x;e.__i32_store8=c.y;e.__i32_store16=c.z;e.__i32_store=c.A;e.__f32_store=c.B;e.__f64_store=c.C;e.__i32_load8_s=c.D;e.__i32_load8_u=c.E;e.__i32_load16_s=c.F;e.__i32_load16_u=c.G;e.__i32_load=c.H;e.__f32_load=c.I;e.__f64_load=c.J;H--;e.monitorRunDependencies?.(H);0==H&&I&&
(c=I,I=null,c());return Y}H++;e.monitorRunDependencies?.(H);var b={a:pa};if(e.instantiateWasm)return new Promise(c=>{e.instantiateWasm(b,(d,f)=>{c(a(d,f))})});K??=e.locateFile?e.locateFile("cyth.wasm",t):t+"cyth.wasm";return a((await da(b)).instance)})();
function Z(){function a(){e.calledRun=!0;if(!A){Y.q();e.onRuntimeInitialized?.();if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;){var b=e.postRun.shift();O.push(b)}N(O)}}if(0<H)I=Z;else{if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)ha();N(P);0<H?I=Z:e.setStatus?(e.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>e.setStatus(""),1);a()},1)):a()}}
if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.shift()();Z();
