var d;d||=typeof Module != 'undefined' ? Module : {};var aa=!!globalThis.window,k=!!globalThis.WorkerGlobalScope,l=globalThis.process?.versions?.node&&"renderer"!=globalThis.process?.type,m="./this.program",n=(a,c)=>{throw c;},p=globalThis.document?.currentScript?.src;"undefined"!=typeof __filename?p=__filename:k&&(p=self.location.href);var q="",r,t;
if(l){var fs=require("fs");q=__dirname+"/";t=a=>{a=u(a)?new URL(a):a;return fs.readFileSync(a)};r=async a=>{a=u(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(m=process.argv[1].replace(/\\/g,"/"));process.argv.slice(2);"undefined"!=typeof module&&(module.exports=d);n=(a,c)=>{process.exitCode=a;throw c;}}else if(aa||k){try{q=(new URL(".",p)).href}catch{}k&&(t=a=>{var c=new XMLHttpRequest;c.open("GET",a,!1);c.responseType="arraybuffer";c.send(null);return new Uint8Array(c.response)});
r=async a=>{if(u(a))return new Promise((b,e)=>{var f=new XMLHttpRequest;f.open("GET",a,!0);f.responseType="arraybuffer";f.onload=()=>{200==f.status||0==f.status&&f.response?b(f.response):e(f.status)};f.onerror=e;f.send(null)});var c=await fetch(a,{credentials:"same-origin"});if(c.ok)return c.arrayBuffer();throw Error(c.status+" : "+c.url);}}var w=console.log.bind(console),x=console.error.bind(console),y,z=!1,u=a=>a.startsWith("file://"),A,B,C,D;
function E(){var a=F.buffer;new Int8Array(a);new Int16Array(a);d.HEAPU8=A=new Uint8Array(a);new Uint16Array(a);B=new Int32Array(a);C=new Uint32Array(a);new Float32Array(a);new Float64Array(a);D=new BigInt64Array(a);new BigUint64Array(a)}function G(a){d.onAbort?.(a);a="Aborted("+a+")";x(a);z=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var H;
async function ba(a){if(!y)try{var c=await r(a);return new Uint8Array(c)}catch{}if(a==H&&y)a=new Uint8Array(y);else if(t)a=t(a);else throw"both async and sync fetching of the wasm failed";return a}async function ca(a,c){try{var b=await ba(a);return await WebAssembly.instantiate(b,c)}catch(e){x(`failed to asynchronously prepare wasm: ${e}`),G(e)}}
async function da(a){var c=H;if(!y&&!u(c)&&!l)try{var b=fetch(c,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(b,a)}catch(e){x(`wasm streaming compile failed: ${e}`),x("falling back to ArrayBuffer instantiation")}return ca(c,a)}class ea{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}var I=a=>{for(;0<a.length;)a.shift()(d)},M=[],N=[],fa=()=>{var a=d.preRun.shift();N.push(a)},O=0,P=null,Q=!0;
class ia{constructor(a){this.L=a-24}}
var R=0,ja=0,ka=globalThis.TextDecoder&&new TextDecoder,la=(a,c=0,b,e)=>{var f=c;b=f+b;if(e)e=b;else{for(;a[f]&&!(f>=b);)++f;e=f}if(16<e-c&&a.buffer&&ka)return ka.decode(a.subarray(c,e));for(f="";c<e;)if(b=a[c++],b&128){var g=a[c++]&63;if(192==(b&224))f+=String.fromCharCode((b&31)<<6|g);else{var h=a[c++]&63;b=224==(b&240)?(b&15)<<12|g<<6|h:(b&7)<<18|g<<12|h<<6|a[c++]&63;65536>b?f+=String.fromCharCode(b):(b-=65536,f+=String.fromCharCode(55296|b>>10,56320|b&1023))}}else f+=String.fromCharCode(b);return f},
S=(a,c,b)=>{var e=A;if(!(0<b))return 0;var f=c;b=c+b-1;for(var g=0;g<a.length;++g){var h=a.codePointAt(g);if(127>=h){if(c>=b)break;e[c++]=h}else if(2047>=h){if(c+1>=b)break;e[c++]=192|h>>6;e[c++]=128|h&63}else if(65535>=h){if(c+2>=b)break;e[c++]=224|h>>12;e[c++]=128|h>>6&63;e[c++]=128|h&63}else{if(c+3>=b)break;e[c++]=240|h>>18;e[c++]=128|h>>12&63;e[c++]=128|h>>6&63;e[c++]=128|h&63;g++}}e[c]=0;return c-f},T={},ma=()=>{if(!U){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",
LANG:("object"==typeof navigator&&navigator.language||"C").replace("-","_")+".UTF-8",_:m||"./this.program"},c;for(c in T)void 0===T[c]?delete a[c]:a[c]=T[c];var b=[];for(c in a)b.push(`${c}=${a[c]}`);U=b}return U},U,na=[null,[],[]],V=[],W,oa=[],pa=a=>{const c=a.length;return[c%128|128,c>>7,...a]},qa={i:127,p:127,j:126,f:125,d:124,e:111},ra=a=>pa(Array.from(a,c=>qa[c]));d.noExitRuntime&&(Q=d.noExitRuntime);d.print&&(w=d.print);d.printErr&&(x=d.printErr);d.wasmBinary&&(y=d.wasmBinary);
d.thisProgram&&(m=d.thisProgram);if(d.preInit)for("function"==typeof d.preInit&&(d.preInit=[d.preInit]);0<d.preInit.length;)d.preInit.shift()();
d.addFunction=(a,c)=>{if(!W){W=new WeakMap;var b=X.length;if(W)for(var e=0;e<0+b;e++){var f;(f=V[e])||(V[e]=f=X.get(e));f&&W.set(f,e)}}if(b=W.get(a)||0)return b;b=oa.length?oa.pop():X.grow(1);try{X.set(b,a),V[b]=X.get(b)}catch(g){if(!(g instanceof TypeError))throw g;c=Uint8Array.of(0,97,115,109,1,0,0,0,1,...pa([1,96,...ra(c.slice(1)),...ra("v"===c[0]?"":c[0])]),2,7,1,1,101,1,102,0,0,7,5,1,1,102,0,0);c=new WebAssembly.Module(c);c=(new WebAssembly.Instance(c,{e:{f:a}})).exports.f;X.set(b,c);V[b]=X.get(b)}W.set(a,
b);return b};d.UTF8ToString=(a,c,b)=>a?la(A,a,c,b):"";
var F,X,sa={a:(a,c,b)=>{var e=new ia(a);C[e.L+16>>2]=0;C[e.L+4>>2]=c;C[e.L+8>>2]=b;R=a;ja++;throw R;},d:function(){return 0},g:function(){return 0},h:function(){},i:()=>G(""),j:(a,c,b,e)=>{var f=(new Date).getFullYear(),g=(new Date(f,0,1)).getTimezoneOffset();f=(new Date(f,6,1)).getTimezoneOffset();C[a>>2]=60*Math.max(g,f);B[c>>2]=Number(g!=f);c=h=>{var v=Math.abs(h);return`UTC${0<=h?"-":"+"}${String(Math.floor(v/60)).padStart(2,"0")}${String(v%60).padStart(2,"0")}`};a=c(g);c=c(f);f<g?(S(a,b,17),
S(c,e,17)):(S(a,e,17),S(c,b,17))},k:function(a,c,b){if(!(0<=a&&3>=a))return 28;D[b>>3]=BigInt(Math.round(1E6*(0===a?Date.now():performance.now())));return 0},l:a=>{var c=A.length;a>>>=0;if(2147483648<a)return!1;for(var b=1;4>=b;b*=2){var e=c*(1+.2/b);e=Math.min(e,a+100663296);a:{e=(Math.min(2147483648,65536*Math.ceil(Math.max(a,e)/65536))-F.buffer.byteLength+65535)/65536|0;try{F.grow(e);E();var f=1;break a}catch(g){}f=void 0}if(f)return!0}return!1},n:(a,c)=>{var b=0,e=0,f;for(f of ma()){var g=c+b;
C[a+e>>2]=g;b+=S(f,g,Infinity)+1;e+=4}return 0},e:(a,c)=>{var b=ma();C[a>>2]=b.length;a=0;for(var e of b){for(var f=b=0;f<e.length;++f){var g=e.charCodeAt(f);127>=g?b++:2047>=g?b+=2:55296<=g&&57343>=g?(b+=4,++f):b+=3}a+=b+1}C[c>>2]=a;return 0},b:()=>52,f:()=>52,m:function(){return 70},c:(a,c,b,e)=>{for(var f=0,g=0;g<b;g++){var h=C[c>>2],v=C[c+4>>2];c+=8;for(var J=0;J<v;J++){var ha=a,K=A[h+J],L=na[ha];0===K||10===K?((1===ha?w:x)(la(L)),L.length=0):L.push(K)}f+=v}C[e>>2]=f;return 0},o:a=>{Q||(d.onExit?.(a),
z=!0);n(a,new ea(a))}};function Y(){function a(){d.calledRun=!0;if(!z){Z.q();d.onRuntimeInitialized?.();if(d.postRun)for("function"==typeof d.postRun&&(d.postRun=[d.postRun]);d.postRun.length;){var c=d.postRun.shift();M.push(c)}I(M)}}if(0<O)P=Y;else{if(d.preRun)for("function"==typeof d.preRun&&(d.preRun=[d.preRun]);d.preRun.length;)fa();I(N);0<O?P=Y:d.setStatus?(d.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>d.setStatus(""),1);a()},1)):a()}}var Z;
(async function(){function a(b){b=Z=b.exports;d._set_error_callback=b.r;d._set_result_callback=b.s;d._run=b.t;d._free=b.u;d._memory_alloc=b.v;d._BinaryenSizeofLiteral=b.w;d._BinaryenSizeofAllocateAndWriteResult=b.x;d.__i32_store8=b.y;d.__i32_store16=b.z;d.__i32_store=b.A;d.__f32_store=b.B;d.__f64_store=b.C;d.__i32_load8_s=b.D;d.__i32_load8_u=b.E;d.__i32_load16_s=b.F;d.__i32_load16_u=b.G;d.__i32_load=b.H;d.__f32_load=b.I;d.__f64_load=b.J;F=b.p;X=b.K;E();O--;d.monitorRunDependencies?.(O);0==O&&P&&(b=
P,P=null,b());return Z}O++;d.monitorRunDependencies?.(O);var c={a:sa};if(d.instantiateWasm)return new Promise(b=>{d.instantiateWasm(c,(e,f)=>{b(a(e,f))})});H??=d.locateFile?d.locateFile("cyth.wasm",q):q+"cyth.wasm";return a((await da(c)).instance)})();Y();
